SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, ROUND(precio * 1.7,2) FROM producto;
SELECT nombre as 'nombre de producto', precio as euros, ROUND(precio * 1.7,2) AS dolares FROM producto;
SELECT UPPER(nombre), UPPER(precio) FROM  producto;
SELECT LOWER(nombre), LOWER(precio) FROM  producto;
SELECT nombre,  UPPER(SUBSTR(nombre,1,2)) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f WHERE codigo_fabricante = f.codigo;
SELECT p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f WHERE codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.codigo, p.nombre, f.codigo, f.nombre FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo;
SELECT p.nombre, precio, f.nombre FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre, precio, f.nombre FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT p.codigo, p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo';
SELECT p.codigo, p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.codigo, p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre REGEXP 'Lenovo|Hewlett-Packard|Seagate';
SELECT p.codigo, p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Lenovo', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, precio FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre REGEXP 'e$';
SELECT p.nombre, precio FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre REGEXP 'w';
SELECT p.nombre, precio, f.nombre FROM producto p JOIN fabricante f ON codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo, f.nombre FROM fabricante f RIGHT JOIN  producto p ON codigo_fabricante = f.codigo;
SELECT * FROM fabricante f LEFT JOIN producto p ON codigo_fabricante = f.codigo;
SELECT * FROM fabricante f LEFT JOIN producto p ON codigo_fabricante = f.codigo WHERE p.codigo IS NULL;
SELECT * FROM producto p LEFT join fabricante f ON codigo_fabricante = f.codigo WHERE f.nombre = 'lenovo';
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'lenovo'));
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM fabricante f INNER JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo');
SELECT * FROM producto p WHERE precio = (SELECT MIN(precio) FROM fabricante f INNER JOIN producto ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Hewlett-Packard');
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM fabricante f INNER JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo');
SELECT * FROM producto WHERE precio > (SELECT AVG(precio) FROM fabricante INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = 'Lenovo');